version: '3'

services:
    web:
        build: .
        command: gunicorn categoriesAPI.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - .:/code
        env_file: .env
        ports:
            - "8000:8000"