# Generated by Django 3.0.2 on 2020-01-20 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the category', max_length=255, unique=True)),
                ('parent', models.ForeignKey(help_text='Parent of the category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='categories.Category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
